site_name: psyphy
site_description: Psychophysical modeling and adaptive trial placement
site_url: https://hmd101.github.io/psyphy/
repo_url: https://github.com/hmd101/psyphy
repo_name: hmd101/psyphy

theme:
  name: material
  logo: reference/images/psyphy_logo_draft.png    
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - toc.integrate
  palette:
    - scheme: default        # Light mode
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate          # Dark mode
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Custom colors via CSS
extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - mkdocstrings: # auto-generate API reference from docstrings
      default_handler: python
      handlers:
        python:
          paths: [.]
          inventories:
            - https://docs.python.org/3/objects.inv
            - https://pytorch.org/docs/stable/objects.inv
          options: # See https://mkdocstrings.github.io/python/usage/
            annotations_path: brief
            docstring_style: numpy
            docstring_section_style: table
            heading_level: 1
            members_order: alphabetical
            inherited_members: true
            filters:
              - "!^_"
              - "!^__"
            merge_init_into_class: true
            parameter_headings: false
            separate_signature: true
            show_if_no_docstring: true
            show_labels: false
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_source: true
            show_submodules: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary:
              modules: false
              classes: true
              functions: true
              attributes: true
  - markdown-exec # Execute code blocks in markdown files


markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true  
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
      base_path: ["docs/examples/", "."]
      dedent_subsections: true # If code is extracted from a file, dedent it.

nav:
  - Home: index.md
  - Usage: usage.md
  - Reference:
      - Overview: reference/overview.md
      - Data: reference/data.md
      - Model: reference/model.md
      - Inference: reference/inference.md
      - Posterior: reference/posterior.md
      - Trial Placement: reference/trial_placement.md
      - Session: reference/session.md
      - Utils: reference/utils.md
   - Examples:
   - Contributing: CONTRIBUTING.md

